spring:
  application:
    name: PIZZA-SERVICE
  datasource:

    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/PizzaServiceDB;AUTO_SERVER=TRUE
    username: sa
    password: sa

    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/PizzaMicroServiceDB
    #username: root
    #password: root
  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9090
  servlet:
    context-path: /api

app:
  rabbitmq:
    add-pizzas-routingkey: q.add-pizzas-to-restaurant
    pizzas-added-routingkey: q.pizzas-added-to-restaurant
    notify-pizzas-added-to-restaurant-routingkey: q.notify-pizzas-added-to-restaurant



