spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - uri: lb://PIZZA-SERVICE
          predicates:
            - Path=/api/pizzas/**, /api/toppings/**
        - uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/api/restaurants/**, /api/drivers/**
  #  PERMETTONO DI COLLEGARSI AD EUREKA SERVER E PRENDERE GLI URL
  # gli altri serviz asta che si colleghino alla porta 8080 e chiamare il path deòòa risorsa


server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
