spring:
  application:
    name: NOTIFICATION-SERVICE

app:
  rabbitmq:
    notify-pizzas-added-to-restaurant-routingkey: q.notify-pizzas-added-to-restaurant

server:
  port: 0  # significa scegli tu una porta libera

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
