spring:
  application:
    name: PIZZA-SERVICE
  #Le proprieta di configurazione sono state spostate al service Config
  config:
    import: optional:configserver:http://localhost:8888/config
  profiles:
    active: prod
